### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ugreg**
Sometimes still face issues even after setting execution policy.

### CODE REVIEW

**Review by jmprieur — APPROVED** [review]
LGTM. 
Thanks @gregdegruy 

@TiagoBrenck @kalyankrishna1 : do you think we want to add this to the AppCreateScript.md generator?

**Comment by TiagoBrenck** [comment]
There is a typo in the sentence. Please update to:
Or if you're still facing issues, go to the containing folder of the configure script and run in PowerShell:

**Comment by ugreg** [comment]
Thanks Tiago I have updated this.

**Comment by bgavrilMS** [comment]
No other users complaining about this. Closing.

**Pull request closed without merging**
