### PR TITLE
Fixing the app creation scripts

### PR DESCRIPTION
**Pull request by jmprieur**
after the renaming in the parameters.json

### CODE REVIEW

**Comment by jmprieur** [comment]
@abhidnya13 : if this works for you, I'll let you merge ....

**Comment by jmprieur** [comment]
cc: @rayluo

**Review by abhidnya13 — APPROVED** [review]

**Comment by abhidnya13** [comment]
Thanks @jmprieur :shipit:

**Review by navyasric — APPROVED** [review]
Looks good!

**Comment by rayluo** [comment]
+1 on [this](https://github.com/Azure-Samples/ms-identity-python-daemon/pull/6#issuecomment-548059863) :-)

**Pull request merged**
